Repository dzemlianoi-double/jobs-front, pull requests merged in 2018-09, with the labels that each got.

#41 autosuggest added
  package-lock.json
  package.json
  src/assets/styles/_helpers.scss
  src/assets/styles/_vacancies.scss
  src/assets/styles/autosuggestion.scss
  src/pages/NotFound.js
  src/pages/services/components/Root.js
  src/pages/vacancies/components/BasicInfo.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/Search.js
  src/pages/vacancies/components/filters/FilterCountry.js
  src/pages/vacancies/components/filters/FilterService.js
  src/pages/vacancies/components/search/SearchAutosuggestions.js
  src/pages/vacancies/components/search/index.js
Labels: in progress

#45 added validate
  package-lock.json
  src/pages/NotFound.js
  src/pages/home/components/header_slider/HeaderSlide.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/Search.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancies/components/VacancyForm.js
  src/pages/vacancies/components/VacancyModal.js
  src/pages/vacancies/components/form/index.js
  src/pages/vacancies/components/form/renderField.js
  src/pages/vacancies/components/search/index.js
  src/pages/vacancies/reducers/index.js
  src/translations/ru.json
Labels: in progress, review

#46 vacancy fixed
  package-lock.json
  src/assets/images/contacts/map-icon.png
  src/assets/styles/_contacts.scss
  src/assets/styles/_helpers.scss
  src/assets/styles/_vacancies.scss
  src/pages/contacts/components/Map.js
  src/pages/contacts/components/Root.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/Search.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancies/components/filters/FilterService.js
  src/pages/vacancies/components/search/SearchAutosuggestions.js
  src/pages/vacancies/components/search/index.js
  src/pages/vacancy/Root.js
  src/translations/ru.json
Labels: finished

#49 added label-hot
  package-lock.json
  package.json
  src/assets/images/hot-img.png
  src/assets/images/img_feedback.jpg
  src/assets/styles/_clients-say.scss
  src/assets/styles/_helpers.scss
  src/assets/styles/_vacancies.scss
  src/assets/styles/autosuggestion.scss
  src/layout/header.js
  src/pages/home/components/Root.js
  src/pages/home/components/counters/CounterSection.js
  src/pages/home/components/counters/index.js
  src/pages/home/components/header_slider/index.js
  src/pages/home/components/last_vacancies/index.js
  src/pages/home/components/reviews/index.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancies/components/search/SearchAutosuggestions.js
Labels: in progress

#54 fix search, fix modal window
  src/assets/styles/_vacancies.scss
  src/assets/styles/autosuggestion.scss
  src/pages/vacancies/components/VacancyModal.js
  src/pages/vacancies/components/form/index.js
  src/pages/vacancies/components/search/SearchAutosuggestions.js
  src/translations/ru.json
Labels: needs review

#56 added modal-window/service
  src/assets/styles/_counter.scss
  src/assets/styles/_media.scss
  src/assets/styles/_pricing.scss
  src/assets/styles/_vacancies.scss
  src/assets/styles/style.scss
  src/pages/contacts/actions/index.js
  src/pages/services/actions/index.js
  src/pages/services/components/Root.js
  src/pages/services/components/Service.js
  src/pages/services/components/ServiceForm.js
  src/pages/services/components/ServiceModal.js
  src/pages/services/reducers/index.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancies/components/search/SearchAutosuggestions.js
Labels: finished, needs review

#57 added default img
  src/assets/images/default_img_vacancy.jpg
  src/assets/images/label_hot.png
  src/assets/styles/_clients-say.scss
  src/assets/styles/_vacancies.scss
  src/assets/styles/_vacancy.scss
  src/pages/home/components/last_vacancies/LastVacancy.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancy/Root.js
Labels: :warning: DO NOT MERGE, needs discuss, needs review

#60 fixed implemented
  package-lock.json
  src/assets/styles/_vacancies.scss
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/Search.js
  src/pages/vacancies/components/search/SearchAutosuggestions.js
Labels: finished

#62 vacancies improved
  package-lock.json
  package.json
  src/pages/about_us/components/Root.js
  src/pages/vacancies/actions/index.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/search/SearchAutosuggestions.js
  src/pages/vacancies/reducers/index.js
  src/pages/vacancy/DescriptionVacancy.js
  src/translations/ru.json
Labels: finished

#64 filters canceling added
  package-lock.json
  package.json
  src/assets/styles/_vacancies.scss
  src/pages/vacancies/actions/index.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/filters/FilterExperience.js
  src/pages/vacancies/components/filters/UsedFilters.js
  src/pages/vacancies/components/filters/index.js
  src/pages/vacancies/reducers/index.js
  src/pages/validateForm.js
  src/translations/ru.json
Labels: finished

#65 sorting added
  src/pages/vacancies/actions/index.js
  src/pages/vacancies/components/BasicInfo.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/Sorting.js
  src/pages/vacancies/reducers/index.js
Labels: finished

#67 shares added
  index.html
  package-lock.json
  package.json
  src/assets/styles/_header.scss
  src/assets/styles/_helpers.scss
  src/pages/vacancies/components/Vacancy.js
  src/translations/ru.json
Labels: finished

#68 fix sorting in BasicInfo
  src/assets/styles/_helpers.scss
  src/assets/styles/_vacancies.scss
  src/pages/vacancies/components/BasicInfo.js
  src/pages/vacancies/components/Sorting.js
  src/pages/vacancies/components/filters/UsedFilters.js
  src/translations/ru.json
Labels: needs discuss, needs review

#70 Feature/buttons share vacancy
  package-lock.json
  src/assets/styles/_about-us.scss
  src/assets/styles/_header.scss
  src/assets/styles/_media.scss
  src/assets/styles/_vacancies.scss
  src/assets/styles/_vacancy.scss
  src/assets/styles/_variables.scss
  src/pages/about_us/components/Root.js
  src/pages/about_us/components/WhoWe.js
  src/pages/vacancies/components/ShareButtons.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancy/InfoVacancy.js
  src/translations/ru.json
Labels: finished
