Repository dzemlianoi-double/jobs-front, pull requests merged in 2018-08, with the labels that each got.

#1 added layout header
  config/scss-lint.config.yml
  package-lock.json
  package.json
  src/assets/images/bg.jpeg
  src/assets/styles/_basic.scss
  src/assets/styles/_header.scss
  src/assets/styles/_helpers.scss
  src/assets/styles/_media.scss
  src/assets/styles/index.js
  src/assets/styles/style.scss
  src/layout/header.js
Labels: question

#2 added layout footer
  src/assets/images/logo.png
  src/assets/styles/_basic.scss
  src/assets/styles/_footer.scss
  src/assets/styles/_media.scss
  src/assets/styles/index.js
  src/layout/footer.js
  src/layout/header.js
Labels: question

#4 Rewrite scss _basic.scss
  src/assets/styles/_basic.scss
Labels: wontfix

#5 added routing
  .eslintrc.js
  package-lock.json
  package.json
  src/app.js
  src/index.js
  src/layout/about-us.js
  src/layout/footer.js
  src/layout/header.js
  src/layout/home.js
  src/layout/main.js
  src/layout/portfolio.js
  src/layout/services.js
  src/reducers.js
Labels: wontfix

#7 Fix/small fixes
  .eslintrc.js
  config/webpack.config.js
  package-lock.json
  package.json
  src/app.js
  src/translations/ru.json
Labels: finished

#8 header-footer-optimization
  .eslintrc.js
  config/webpack.config.js
  src/app.js
  src/layout/footer.js
  src/layout/header.js
  src/store/translations.js
  src/translations/ru.json
Labels: finished

#10 Feature/spinner
  package.json
  src/app.js
  src/assets/styles/_variables.scss
  src/assets/styles/spinner.scss
  src/assets/styles/style.scss
  src/layout/main.js
  src/layout/spinner.js
Labels: finished

#12 added logo, fix footer style
  src/assets/images/bg.jpeg
  src/assets/images/logo.png
  src/assets/images/worker_logo.png
  src/assets/styles/_footer.scss
  src/assets/styles/_header.scss
  src/assets/styles/fonts/9119.ttf
  src/assets/styles/spinner.scss
  src/layout/footer.js
  src/layout/header.js
  src/translations/ru.json
Labels: help wanted

#13 Footer/fix layout
  sass-lint.config.yml
  src/app.js
  src/assets/images/error-bg.jpg
  src/assets/styles/_footer.scss
  src/assets/styles/_header.scss
  src/assets/styles/_not-found.scss
  src/assets/styles/style.scss
  src/config/external_routes.js
  src/layout/footer.js
  src/layout/header.js
  src/layout/main.js
  src/layout/not-found.js
  src/pages/contacts/actions/index.js
  src/pages/vacancies/actions/index.js
  src/pages/vacancies/reducers/jobs.js
  src/reducers.js
Labels: review

#14 fix routing
  src/app.js
  src/layout/main.js
Labels: finished

#16 Additional home parts added
  package-lock.json
  package.json
  src/assets/styles/style.scss
  src/layout/home.js
  src/layout/main.js
  src/pages/home/components/HeaderSlider.js
  src/pages/home/components/WhoWe.js
  src/pages/home/components/home.js
Labels: finished

#17 added map, layout contacts page, fix scss
  package-lock.json
  package.json
  src/assets/images/about-us.jpg
  src/assets/styles/_who-we.scss
  src/assets/styles/contacts.scss
  src/assets/styles/style.scss
  src/config/internal_routes.js
  src/index.js
  src/layout/about-us.js
  src/layout/contacts.js
  src/layout/footer.js
  src/layout/header.js
  src/layout/main.js
  src/layout/map.js
  src/layout/portfolio.js
  src/pages/home/components/WhoWe.js
  src/pages/home/components/home.js
  src/translations/ru.json
Labels: review

#18 Feature/prepare project
  package.json
  src/app.js
  src/assets/styles/_header.scss
  src/assets/styles/_helpers.scss
  src/config/internal_routes.js
  src/layout/footer.js
  src/layout/header.js
  src/layout/main.js
  src/layout/not-found.js
  src/pages/NotFound.js
  src/pages/about_us/components/Root.js
  src/pages/basic/components/Spinner.js
  src/pages/contacts/components/Map.js
  src/pages/contacts/components/Root.js
  src/pages/home/components/Root.js
  src/pages/home/components/WhoWe.js
  src/pages/services/components/Root.js
  src/pages/vacancies/components/Root.js
  src/translations/ru.json
Labels: finished

#19 fix carousel
  src/app.js
  src/assets/images/answ1.jpg
  src/assets/images/answ2.jpg
  src/assets/images/answ3.jpg
  src/assets/images/office.jpg
  src/assets/images/slider_1.jpg
  src/assets/images/slider_2.jpg
  src/assets/images/slider_3.jpg
  src/assets/images/slider_4.jpg
  src/assets/images/slider_5.jpg
  src/assets/images/worker_slider.jpg
  src/assets/styles/_basic.scss
  src/assets/styles/_clients-say.scss
  src/assets/styles/_helpers.scss
  src/assets/styles/_slick.scss
  src/assets/styles/_slider.scss
  src/assets/styles/_who-we.scss
  src/assets/styles/style.scss
  src/pages/home/components/ClientsSay.js
  src/pages/home/components/HeaderSlider.js
  src/pages/home/components/Root.js
  src/pages/home/components/WhoWe.js
Labels: review

#23 added vacancies page
  src/assets/images/arrow_long.png
  src/assets/images/house.png
  src/assets/images/location_mini.png
  src/assets/images/search_ico_sm.png
  src/assets/images/search_small.png
  src/assets/styles/_helpers.scss
  src/assets/styles/_vacancies.scss
  src/assets/styles/style.scss
  src/pages/vacancies/components/Root.js
Labels: review

#24 fixes implemented
  .gitignore
  src/layout/footer.js
  src/pages/basic/actions/index.js
  src/pages/basic/reducers/basic.js
  src/pages/home/components/ClientsSay.js
  src/pages/home/components/Counter.js
  src/pages/home/components/CounterSection.js
  src/pages/home/components/Review.js
Labels: finished

#25 add dynamic to card
  package-lock.json
  package.json
  src/assets/styles/_helpers.scss
  src/assets/styles/_vacancies.scss
  src/config/external_routes.js
  src/pages/vacancies/actions/index.js
  src/pages/vacancies/components/BasicInfo.js
  src/pages/vacancies/components/Filters.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/Search.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancies/reducers/index.js
  src/reducers.js
Labels: finished

#26 fix scss left 2 warnings
  sass-lint.config.yml
  src/assets/images/operator.jpg
  src/assets/images/operator1.jpg
  src/assets/styles/_basic.scss
  src/assets/styles/_call-back.scss
  src/assets/styles/_clients-say.scss
  src/assets/styles/_footer.scss
  src/assets/styles/_header.scss
  src/assets/styles/_helpers.scss
  src/assets/styles/_media.scss
  src/assets/styles/_not-found.scss
  src/assets/styles/_slick.scss
  src/assets/styles/_slider.scss
  src/assets/styles/_vacancies.scss
  src/assets/styles/_variables.scss
  src/assets/styles/_who-we.scss
  src/assets/styles/contacts.scss
  src/assets/styles/counter.scss
  src/assets/styles/slick.scss
  src/assets/styles/style.scss
  src/pages/contacts/components/Root.js
  src/pages/home/components/CallBack.js
  src/pages/home/components/ClientsSay.js
  src/pages/home/components/HeaderSlider.js
  src/pages/home/components/Root.js
  src/pages/home/components/WhoWe.js
  src/pages/vacancies/components/Root.js
Labels: review

#29 add filters
  src/assets/styles/_vacancies.scss
  src/pages/vacancies/actions/index.js
  src/pages/vacancies/components/Filters.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancies/components/filters/FilterAge.js
  src/pages/vacancies/components/filters/FilterCountry.js
  src/pages/vacancies/components/filters/FilterExperience.js
  src/pages/vacancies/components/filters/FilterSalary.js
  src/pages/vacancies/components/filters/FilterService.js
  src/pages/vacancies/components/filters/FilterSex.js
  src/pages/vacancies/components/filters/index.js
  src/pages/vacancies/reducers/index.js
Labels: finished

#30 add filter sex and country
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/filters/FilterCountry.js
  src/pages/vacancies/components/filters/FilterSex.js
  src/pages/vacancies/components/filters/index.js
  src/pages/vacancies/reducers/index.js
Labels: finished

#31 add filters for Service
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/filters/FilterCountry.js
  src/pages/vacancies/components/filters/FilterService.js
  src/pages/vacancies/components/filters/index.js
  src/pages/vacancies/reducers/index.js
Labels: finished

#33 Added/vacancy page
  src/assets/images/house_1.jpg
  src/assets/styles/_contacts.scss
  src/assets/styles/_counter.scss
  src/assets/styles/_footer.scss
  src/assets/styles/_pricing.scss
  src/assets/styles/_services.scss
  src/assets/styles/_spinner.scss
  src/assets/styles/_vacancies.scss
  src/assets/styles/_vacancy.scss
  src/assets/styles/style.scss
  src/config/internal_routes.js
  src/layout/main.js
  src/pages/basic/actions/index.js
  src/pages/basic/reducers/basic.js
  src/pages/home/components/LastVacancies.js
  src/pages/home/components/Root.js
  src/pages/home/components/SliderLastVacancies.js
  src/pages/home/components/WhoWe.js
  src/pages/services/components/BasicInfo.js
  src/pages/services/components/Root.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancy/Root.js
Labels: review

#32 style buttons
  src/assets/styles/_vacancies.scss
  src/pages/vacancies/components/filters/FilterAge.js
  src/pages/vacancies/components/filters/FilterButton.js
  src/pages/vacancies/components/filters/FilterCountry.js
  src/pages/vacancies/components/filters/FilterExperience.js
  src/pages/vacancies/components/filters/FilterSalary.js
  src/pages/vacancies/components/filters/FilterService.js
  src/pages/vacancies/components/filters/FilterSex.js
Labels: finished

#36 added react-modal
  favicon.ico
  package-lock.json
  package.json
  src/assets/images/favicon.ico
  src/assets/styles/_header.scss
  src/layout/footer.js
  src/layout/header.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancies/components/VacancyModal.js
  webpack.config.js
Labels: review

#39 major fixes implemented
  src/app.js
  src/assets/images/home/header_slider/1.jpg
  src/assets/images/home/header_slider/2.jpg
  src/assets/images/home/header_slider/3.jpg
  src/assets/styles/_basic.scss
  src/assets/styles/_pricing.scss
  src/layout/footer.js
  src/layout/header.js
  src/layout/main.js
  src/pages/basic/components/Only.js
  src/pages/home/components/ClientsSay.js
  src/pages/home/components/HeaderSlider.js
  src/pages/home/components/Root.js
  src/pages/home/components/Services.js
  src/pages/home/components/SliderLastVacancies.js
  src/pages/home/components/WhoWe.js
  src/pages/home/components/counters/CounterSection.js
  src/pages/home/components/counters/index.js
  src/pages/home/components/header_slider/header_slide.js
  src/pages/home/components/header_slider/index.js
  src/pages/home/components/last_vacancies/LastVacancy.js
  src/pages/home/components/last_vacancies/index.js
  src/pages/home/components/reviews/Review.js
  src/pages/home/components/reviews/index.js
  src/pages/home/components/services/Service.js
  src/pages/home/components/services/index.js
  src/pages/services/components/Root.js
  src/pages/services/components/Service.js
  src/pages/vacancies/actions/index.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancies/components/VacancyForm.js
Labels: finished

#40 Feature/vacancy page
  favicon.ico
  package-lock.json
  package.json
  src/assets/styles/_basic.scss
  src/assets/styles/_clients-say.scss
  src/assets/styles/_counter.scss
  src/assets/styles/_header.scss
  src/assets/styles/_helpers.scss
  src/assets/styles/_services.scss
  src/assets/styles/_slider.scss
  src/assets/styles/_spinner.scss
  src/assets/styles/_vacancy.scss
  src/assets/styles/_who-we.scss
  src/assets/styles/fonts/9119.ttf
  src/assets/styles/fonts/NewBaskervilleC Bold.ttf
  src/assets/styles/fonts/Pacifico-Regular.ttf
  src/assets/styles/style.scss
  src/layout/footer.js
  src/layout/header.js
  src/layout/main.js
  src/pages/contacts/components/Root.js
  src/pages/home/components/CallBack.js
  src/pages/home/components/WhoWe.js
  src/pages/home/components/counters/CounterSection.js
  src/pages/home/components/counters/index.js
  src/pages/home/components/header_slider/HeaderSlide.js
  src/pages/home/components/header_slider/index.js
  src/pages/home/components/last_vacancies/LastVacancy.js
  src/pages/home/components/services/index.js
  src/pages/vacancy/LastVacancies.js
  src/pages/vacancy/Root.js
  src/translations/ru.json
Labels: help wanted, review

#42 fix vacancies
  package-lock.json
  package.json
  src/assets/images/about-us.jpg
  src/assets/images/favicon.ico
  src/assets/images/home/header_slider/3.jpg
  src/assets/images/house_1.jpg
  src/assets/styles/_not-found.scss
  src/layout/footer.js
  src/pages/NotFound.js
  src/pages/contacts/components/Map.js
  src/pages/home/components/counters/index.js
  src/pages/home/components/header_slider/index.js
  src/pages/services/components/Root.js
  src/pages/services/components/Service.js
  src/pages/vacancies/components/BasicInfo.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/Search.js
  src/pages/vacancies/components/Vacancy.js
  src/pages/vacancies/components/VacancyForm.js
  src/pages/vacancies/components/VacancyModal.js
  src/pages/vacancies/components/filters/FilterAge.js
  src/pages/vacancies/components/filters/FilterButton.js
  src/pages/vacancies/components/filters/FilterCountry.js
  src/pages/vacancies/components/filters/FilterExperience.js
  src/pages/vacancies/components/filters/FilterSalary.js
  src/pages/vacancies/components/filters/FilterService.js
  src/pages/vacancies/components/filters/FilterSex.js
  src/pages/vacancy/LastVacancies.js
  src/pages/vacancy/Root.js
  src/pages/vacancy/SliderLastVacancies.js
  src/translations/ru.json
Labels: help wanted, in progress, review

#43 Feature/after review fixes
  src/assets/styles/_header.scss
  src/assets/styles/_media.scss
  src/assets/styles/_pricing.scss
  src/pages/services/components/Service.js
  src/pages/vacancies/components/Root.js
  src/pages/vacancies/components/filters/index.js
  src/translations/ru.json
Labels: finished
